# Generated by Django 3.0.2 on 2020-03-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified', models.CharField(max_length=100)),
                ('frank_anno', models.CharField(max_length=600, null=True)),
                ('adduct', models.CharField(max_length=100)),
                ('confidence', models.IntegerField(default=0)),
                ('neutral_mass', models.DecimalField(decimal_places=10, max_digits=20)),
                ('annotation_group', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpd_formula', models.CharField(max_length=100)),
                ('pc_sec_id', models.IntegerField()),
                ('chebi_id', models.CharField(max_length=30, null=True, unique=True)),
                ('chebi_name', models.CharField(max_length=250, null=True)),
                ('inchikey', models.CharField(max_length=27, null=True)),
                ('smiles', models.CharField(max_length=250, null=True)),
                ('cas_code', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psec_id', models.IntegerField(unique=True)),
                ('m_z', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rt', models.DecimalField(decimal_places=10, max_digits=20)),
                ('polarity', models.CharField(max_length=8)),
                ('preferred_annotation_reason', models.CharField(max_length=600)),
                ('preferred_annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_annotation', to='met_explore.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('life_stage', models.CharField(max_length=250)),
                ('tissue', models.CharField(max_length=250)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('mutant', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplePeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.Peak')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundDBDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('cmpd_name', models.CharField(max_length=250)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.Compound')),
                ('db_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.DBNames')),
            ],
            options={
                'ordering': ['db_name'],
            },
        ),
        migrations.AddField(
            model_name='compound',
            name='peaks',
            field=models.ManyToManyField(through='met_explore.Annotation', to='met_explore.Peak'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.Compound'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='peak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.Peak'),
        ),
    ]
