# Generated by Django 3.1.7 on 2021-04-08 15:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
