# Generated by Django 3.1.3 on 2021-02-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='type',
            new_name='ftype',
        ),
    ]
