# Generated by Django 3.0.5 on 2020-09-02 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
