# Generated by Django 2.2.1 on 2019-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='chebi_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
