# Generated by Django 2.1.7 on 2019-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak',
            name='neutral_mass',
        ),
        migrations.AddField(
            model_name='annotation',
            name='neutral_mass',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20),
            preserve_default=False,
        ),
    ]
