# Generated by Django 3.1.3 on 2020-12-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysiscomparison',
            old_name='case_sample',
            new_name='case_group',
        ),
        migrations.RenameField(
            model_name='analysiscomparison',
            old_name='control_sample',
            new_name='control_group',
        ),
    ]
