# Generated by Django 3.1.3 on 2021-01-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0002_auto_20201204_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysiscomparison',
            name='case_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_group', to='met_explore.group'),
        ),
        migrations.AlterField(
            model_name='analysiscomparison',
            name='control_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_group', to='met_explore.group'),
        ),
    ]
