# Generated by Django 3.1.3 on 2021-02-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0002_auto_20210224_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='ftype',
            new_name='type',
        ),
    ]
