# Generated by Django 3.0.5 on 2020-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0003_auto_20200902_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquetoken',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
