# Generated by Django 3.0.5 on 2020-09-03 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0005_auto_20200903_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquetoken',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
