# Generated by Django 3.0.5 on 2020-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0006_auto_20200903_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='related_chebi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
