# Generated by Django 3.1.2 on 2020-10-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0007_compound_related_chebi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.sample')),
            ],
        ),
    ]
