# Generated by Django 3.1.3 on 2020-11-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met_explore', '0009_auto_20201029_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='group',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
