# Generated by Django 3.1.3 on 2020-11-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('met_explore', '0010_sample_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('metadata', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField()),
                ('owner', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='met_explore.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='met_explore.Share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compound',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='met_explore.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peak',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='met_explore.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='met_explore.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniquetoken',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='met_explore.project'),
            preserve_default=False,
        ),
    ]
