CSV_GROUP_COLNAME = 'group'

INITIAL_PROJECT_ID = 1 # assume only one project, TODO: might not be the case
LABEL_METABOLOMICS = 'metabolomics'
LABEL_CATEGORIES = 'categories'
LABEL_PROJECT_CONFIG = 'ui_config'
LABEL_FACTOR_ORDER_DICT = 'factor_order_dict'
LABEL_SEARCH_SECTIONS = 'search_sections'
LABEL_INITIAL_ANALYSIS = 'entry_analysis'
LABEL_ANALYSIS = 'analysis'
LABEL_PROJECT_NAME = 'project_name'
LABEL_PROJECT_DESCRIPTION = 'project_description'
LABEL_SPECIES = 'species'
LABEL_COLOR_SCHEME = 'color_scheme'
LABEL_LOGO_FILENAME = 'logo_filename'
LABEL_LOGO_ALT = 'logo_alt'
LABEL_FOOTER_SHOW = 'footer_show'
LABEL_FOOTER_EMAIl = 'footer_email'
