CSV_GROUP_COLNAME = 'group'

LABEL_METABOLOMICS = 'metabolomics'
LABEL_CATEGORIES = 'categories'
LABEL_PROJECT_CONFIG = 'ui_config'
LABEL_FACTOR_ORDER_DICT = 'factor_order_dict'
LABEL_SEARCH_SECTIONS = 'search_sections'
LABEL_INITIAL_ANALYSIS = 'entry_analysis'
LABEL_ANALYSIS = 'analysis'
LABEL_SPECIES = 'species'
