from django.conf import settings
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views


def c(f, timeout=60 * 18000):
    """
    Cache the page generated by view function f
    timeout: how long to cache
    """
    if settings.CACHE_VIEWS:
        return cache_page(timeout)(f)
    else:
        return f


urlpatterns = [
    path('', views.index, name='met_explore_index'),

    # general views
    path('background', views.background, name='background'),
    path('credits', views.credits, name='credits'),
    path('glossary', views.glossary, name='glossary'),
    path('exp_protocols', views.exp_protocols, name='exp_protocols'),
    path('feedback', views.feedback, name='feedback'),
    path('links', views.links, name='links'),
    path('about', views.about, name='about'),
    path('plate/', include('django_spaghetti.urls')),

    # Metabolomics views
    path('met_ex_all/<int:analysis_id>/<str:cmpd_list>', views.met_ex_all, name='met_ex_all'),
    path('met_ex_tissues/<int:analysis_id>', views.met_ex_tissues, name='met_ex_tissues'),
    path('metabolite_search/<int:analysis_id>', views.metabolite_search, name='metabolite_search'),
    path('met_search_highchart_data/<str:analysis_id>/<str:tissue>/<str:metabolite>', views.met_search_highchart_data,
         name='met_search_highchart_data'),
    path('metabolite_data/<str:cmpd_ids>', c(views.metabolite_data), name='metabolite_data'),
    path('metabolite_peak_data/<int:cmpd_id>', views.metabolite_peak_data, name='metabolite_peak_data'),
    path('get_metabolite_names', views.get_metabolite_names, name='get_metabolite_names'),
    path('peak_explore_annotation_data/<int:peak_id>', views.peak_explore_annotation_data,
         name='peak_explore_annotation_data'),
    path('get_pathway_names/<int:analysis_id>', views.get_pathway_names, name='get_pathway_names'),
    path('metabolite_pathway_data/<str:analysis_id>/<str:pw_id>', views.metabolite_pathway_data,
         name='metabolite_pathway_data'),
    path('pathway_search/<int:analysis_id>', views.pathway_search, name='pathway_search'),
    path('pathway_metabolites/<int:analysis_id>', views.pathway_metabolites, name='pathway_metabolites'),
    path('pathway_explorer/<int:analysis_id>', views.pathway_explorer, name='pathway_explorer'),
    path('pals_data/<int:analysis_id>', c(views.pals_data), name='pals_data'),
    path('peak_explorer/<int:analysis_id>/<str:peak_list>', c(views.peak_explorer), name='peak_explorer'),
    path('peak_data/<int:analysis_id>/<str:peak_list>', c(views.peak_data), name='peak_data'),
    path('peak_ex_compare/<int:analysis_id>/<str:peak_compare_list>', c(views.peak_ex_compare), name='peak_ex_compare'),
    path('peak_compare_data/<int:analysis_id>/<str:peak_compare_list>', c(views.peak_compare_data),
         name='peak_compare_data'),
    path('peak_mf_compare/<int:analysis_id>', views.peak_mf_compare, name='peak_mf_compare'),
    path('peak_mf_compare_data/<int:analysis_id>', c(views.peak_mf_compare_data), name='peak_mf_age_data'),

    # Enzyme specific views

    path('enzyme_search', views.enzyme_search, name='enzyme_search'),

]
