from django.urls import path, include
from . import views
from django.views.decorators.cache import cache_page

def c(f, timeout=60 * 18000):
    """
    Cache the page generated by view function f
    timeout: how long to cache
    """
    return cache_page(timeout)(f)

urlpatterns = [
    path('', views.index, name='met_explore_index'),

    # other views
    path('background', views.background, name='background'),
    path('credits', views.credits, name='credits'),
    path('glossary', views.glossary, name='glossary'),
    path('exp_protocols', views.exp_protocols, name='exp_protocols'),
    path('feedback', views.feedback, name='feedback'),
    path('links', views.links, name='links'),
    path('about', views.about, name='about'),
    path('plate/', include('django_spaghetti.urls')),

    # common views, e.g. peaks, metabolites
    path('met_search_highchart_data/<str:analysis_id>/<str:tissue>/<str:metabolite>', views.met_search_highchart_data, name='met_search_highchart_data'),
    path('metabolite_data/<str:cmpd_ids>', c(views.metabolite_data), name='metabolite_data'),
    path('metabolite_peak_data/<int:cmpd_id>', views.metabolite_peak_data, name='metabolite_peak_data'),
    path('get_metabolite_names', views.get_metabolite_names, name='get_metabolite_names'),
    path('peak_explore_annotation_data/<int:peak_id>', views.peak_explore_annotation_data, name='peak_explore_annotation_data'),
    path('pathway_search', views.pathway_search, name='pathway_search'),
    path('pathway_metabolites', views.pathway_metabolites, name='pathway_metabolites'),
    path('get_pathway_names', views.get_pathway_names, name='get_pathway_names'),
    path('metabolite_pathway_data/<str:pw_id>', views.metabolite_pathway_data, name='metabolite_pathway_data'),
    # path('pathway_search_data/<str:pwy_id>', views.pathway_search_data, name='pathway_search_data'),

    # flymet specific views (TODO: could be made general too?)
    path('met_ex_mutants', views.met_ex_mutants, name='met_ex_mutants'),
    path('met_ex_gconditions', views.met_ex_gconditions, name='met_ex_gconditions'),

    # other views not yet implemented
    path('enzyme_search', views.enzyme_search, name='enzyme_search'),
    path('temp_his_pw', views.temp_his_pw, name='temp_his_pw'),
    path('tissue_metabolites', views.MetaboliteListView.as_view(), name='tissue_metabolites'), # seems unused?
    path('tissue_search', views.tissue_search, name='tissue_search'),
    path('path_ex_lifestages', views.path_ex_lifestages, name='path_ex_lifestages'),

    # tissue-specific views
    path('met_ex_all/<str:cmpd_list>', views.met_ex_all, name='met_ex_all'),
    path('metabolite_search', views.metabolite_search, name='metabolite_search'),
    path('met_ex_tissues', views.met_ex_tissues, name='met_ex_tissues'),
    path('peak_ex_compare/<str:peak_compare_list>', c(views.peak_ex_compare), name='peak_ex_compare'),
    path('peak_mf_compare', views.peak_mf_compare, name='peak_mf_compare'),
    path('peak_explorer/<str:peak_list>', c(views.peak_explorer), name='peak_explorer'),
    path('peak_data/<str:peak_list>', c(views.peak_data), name='peak_data'),
    path('peak_compare_data/<str:peak_compare_list>', c(views.peak_compare_data), name='peak_compare_data'),
    path('peak_mf_compare_data', c(views.peak_mf_compare_data), name='peak_mf_age_data'),
    path('pals_data', c(views.pals_data), name='pals_data'),
    path('pathway_explorer', views.pathway_explorer, name='pathway_explorer'),

    # age-specific views
    path('met_age_all/<str:cmpd_list>', views.met_age_all, name='met_age_all'),
    path('metabolite_search_age', views.metabolite_search_age, name='metabolite_search_age'),
    path('met_age_id', views.met_age_id, name='met_age_id'),
    path('peak_age_compare/<str:peak_compare_list>', c(views.peak_age_compare), name='peak_age_compare'),
    path('peak_mf_age_compare', views.peak_mf_age_compare, name='peak_mf_age_compare'),
    path('peak_age_explorer/<str:peak_list>', c(views.peak_age_explorer), name='peak_age_explorer'),
    path('peak_age_data/<str:peak_list>', c(views.peak_age_data), name='peak_age_data'),
    path('peak_age_compare_data/<str:peak_compare_list>', c(views.peak_age_compare_data), name='peak_age_compare_data'),
    path('peak_mf_age_data', c(views.peak_mf_age_data), name='peak_mf_age_data'),
    path('pals_age_data', c(views.pals_age_data), name='pals_age_data'),
    path('pathway_age_explorer', views.pathway_age_explorer, name='pathway_age_explorer'),
]